### ISSUE TITLE
Automatic module name

### ISSUE THREAD

**Issue by stffnjng** [HebiRobotics/MFL#39]
I can't seem to get mfl-core to work with the Jigsaw mess. Apparently hyphens are not allowed in module names?

For example when I run jar ``` --file mfl-core-0.5.1.jar --describe-module``` I get the error ``` Invalid module name: 'mfl-core' is not a Java identifier```

**Comment by stffnjng** [comment]
Removing the hyphens from the ```<automaticModuleName>``` tag and replacing them with colons seems to fix it: https://github.com/stffnjng/MFL/commit/9842729edfe6605c21677042f68eed38a792646f

**Comment by ennerf** [comment]
Thanks for letting me know. That was an oversight on my part.

I've deployed an update to the maven snapshot repo, i.e., `0.5.2-SNAPSHOT`. I'll

**Comment by stffnjng** [comment]
Thanks, works like a charm!
