### ISSUE TITLE
Support for specific Matlab classes

### ISSUE THREAD

**Issue by jkocot** [HebiRobotics/MFL#47]
Not sure if this is really in scope of this library, but I need to read an object of a specific Matlab class, namely, LinearModel (https://uk.mathworks.com/help/stats/linearmodel.html), from a .mat file. The library reads the file, but I cannot identify some of the fields listed at https://uk.mathworks.com/help/stats/linearmodel.html within the resulting object (but there are some others instead) - e.g. 'RSME' or 'Residuals' is missing. I even examined other fields (with different names), but there don't seem to be such that would have similar contents to the ones I look for. Some of the fields, however, are there and have correct values - e.g. 'MSE'.
As they are listed as "Properties" in the Matlab documentation, I would expect them to be there somewehere, unless they are not real properties, but something internally calculated.

**Comment by ennerf** [comment]
I'm considering supporting special wrappers for some of the common base MATLAB types like `string` or `table`, but `LinearModel` would definitely be outside the scope of this library.

That being said, available properties should still show up. If they don't, it probably means that they are calculated internally or that there is a bug with parsing the (undocumented) subsystem.

I unfortunately don't have the statistics toolbox installed, so I can't really debug this by myself. It'd be great if you could upload a sample `.mat` file that is missing properties. That way I can at least do a quick text search through the subsystem to check whether there is any information in an area that is currently being ignored.

**Comment by jkocot** [comment]
Github doesn't support .mat files, but you can download a sample file from here:
https://www.dropbox.com/s/mplq24qdusyjin2/gmpe_model_2.mat?dl=0
After loading the contents, you can read e.g. mdl2.RMSE, or mdl2.Residuals, while listing through  `Mat5.newReader(source).readMat().getEntries();` doesn't show them.

**Comment by ennerf** [comment]
It looks like those properties are not being serialized. There are no strings matching `RMSE` or `Residuals` anywhere in the file.

You can check it yourself via

```Java     
// Read subsystem buffer
ByteBuffer subsysBuffer = Mat5.readFromFile("gmpe_model_2.mat")
     .getSubsystem()
     .getBuffer();

// Write raw bytes to disk
try(ByteChannel out = new RandomAccessFile("gmpe_model_2_subsys.dat", "rw").getChannel()){
    out.write(subsysBuffer);
}
```

The strings are encoded as ascii, so you can just look for strings in a text editor.

Sorry I can't help you. Do you mind if I close this issue?

**Comment by ennerf** [comment]
The `Mat::toString()` is btw. useful for checking everything that's in a file. The output of `System.out.println(Mat5.readFromFile("gmpe_model_2.mat"))` prints the following:

```
Mat5File{description='MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Thu Jun  6 17:07:22 2019', subsysOffset=272, byteOrder=LITTLE_ENDIAN, version=1}
mdl2 = 1x1 LinearModel
    Robust: []
    DummyVarCoding: 'reference'
    CoefTerm: 1x2 double
    DesignMeans: 1x2 double
    TermMeans: 1x1 struct
        Terms: []
        CoefTerm: []
        Means: []
    IsHierarchical: true
    Formula: 1x1 classreg.regr.LinearFormula
        isMultivariate: false
        tree: []
        str: 'logPGA_x ~ 1 + Mw2'
        responseName: 'logPGA_x'
        varNames: 1x2 cell
        link: 'identity'
        terms: 2x2 double
        FunctionCalls: {}
    LogLikelihood: -1326.5466948267886
    DFE: 2237.0
    SSE: 428.7410980112345
    SST: 564.3155212315995
    SSR: 135.57442322036505
    CoefficientCovariance: 2x2 double
    CoefficientNames: 1x2 cell
    LogLikelihoodNull: -1634.1408442642323
    Coefs: 2x1 double
    VariableInfo: 1x1 table
        data: 1x4 cell
        ndims: 2.0
        nrows: 2.0
        rownames: 2x1 cell
        nvars: 4.0
        varnames: 1x4 cell
        props: 1x1 struct
            Description: ''
            UserData: []
            VariableDescriptions: {}
            VariableUnits: {}
            DimensionNames: 1x2 cell
            VersionSavedFrom: 2.0
    PredLocs: 1.0
    RespLoc: 2.0
    IsFitFromData: true
    PredictorTypes: 'mixed'
    ResponseType: 'numeric'
    NumObservations_: 2239.0
    IsFitFromTable: true
    Leverage: 2239x1 double
    Steps: []
    Design: 2239x2 double
    ObservationInfo: 1x1 table
        data: 1x4 cell
        ndims: 2.0
        nrows: 2239.0
        rownames: {}
        nvars: 4.0
        varnames: 1x4 cell
        props: 1x1 struct
            Description: ''
            UserData: []
            VariableDescriptions: {}
            VariableUnits: {}
            DimensionNames: 1x2 cell
            VersionSavedFrom: 2.0
    Data: 1x1 table
        data: 1x2 cell
        ndims: 2.0
        nrows: 2239.0
        rownames: {}
        nvars: 2.0
        varnames: 1x2 cell
        props: 1x1 struct
            Description: ''
            UserData: []
            VariableDescriptions: {}
            VariableUnits: {}
            DimensionNames: 1x2 cell
            VersionSavedFrom: 2.0
    WorkingValues: []
    Q: []
    MSE: 0.1916589620077043
    Qy: 2x1 double
    R: 2x2 double
    Rtol: 1.2058397012460095E-10
    PrivateLogLikelihood: []
"" = 1x130624 uint8
```

**Comment by ennerf** [comment]
One thing you can always do is to just store missing fields as separate variables, e.g.,

```matlab
extraData = struct();
extraData.MSE = mdl2.MSE
extraData.Residuals = mdl2.Residuals;
```

and then just store both together in a single `.mat` file. That way it'll just show up as a standard struct.

**Comment by jkocot** [comment]
> One thing you can always do is to copy the missing fields into a separate variable before saving, i.e.,

This is what I am doing right now, but I was hoping I could skip this step as I am using scripts provided by other people and don't want to intervene much in the code.
Using `mdl2 = struct(mdl2)` is also a nice solution (I didn't think about this before), but, unfortunately, the returned structure is much, much larger (4.3MB vs 128KB) than before.

Anyway, thanks for help (also for the hints on debugging the object contents), and, yes, I guess there was nothing left to do than closing the issue.

**Comment by ennerf** [comment]
Rather than asking users to change their code, you may be able to create a MATLAB script that loads user files and automatically converts/re-saves the data into any format you want. That way you don't rely on user versions and have the ability to add more information later.

pseudo code (I forgot the exact syntax to do this)

```matlab
for file : fileNames(originalDirectory)

    % load file from disk
    content = matFile(file);

    % iterate over contained variables
    for fieldName : fieldnames(content);

      % copy original data
       modifiedContent.(fieldName) = content.(fieldName);

       % store any necessary additional information
        if isa(content.(fieldName), 'LinearModel')
            modifiedContent.([fieldName 'Residuals']) = content.(fieldName).Residuals;
        end

    end

    % save modified data as a new matFile in some other directory

end
```
