### ISSUE TITLE
Read struct contains hidden field of Mat5Subsystem type

### ISSUE THREAD

**Issue by piotrszwarnog** [HebiRobotics/MFL#48]
I have migrated from matfilerw to MFL recently. It is all nice and clear, but there is one thing that have surprised me. 
In one scenario I check if Struct has size of 1 and if so, I perform some operation on that only field. But since migration, using the same test file, check returns that Struct has size of 2. One field is expected 'report' struct and second is unnamed ('') field. Debugging revealed that it is instance of Mat5Subsystem class. I am not daily matlab user - maybe that's normal, but in matlab's workspace only 'report' is field present (same in octave). 
Where that '' field come from? What makes MFL detect that field? 

Link to .mat file https://www.dropbox.com/s/19kaiyqydndcjsc/gmpe_output.mat?dl=0

**Comment by ennerf** [comment]
The Subsystem exists if your file contains reference types like `string`, `table`, or anything that extends from `handle`. You can find a more detailed explanation [here](https://stackoverflow.com/a/56943418/3574093).

Your file contains a `table` in `report.coefficients`.

![image](https://user-images.githubusercontent.com/5491587/63256753-85e8c780-c278-11e9-85ec-14b541b9e40a.png)

The struct only contains the below reference

```
[10] Matrix (128 bytes, position = 920)
      [0] UInt32[2] = [17, 0] // Opaque
      [1] Int8[0] = ['']
      [2] Int8[4] = ['MCOS']
      [3] Int8[5] = ['table']
      [4] Matrix (72 bytes, position = 976)
        [0] UInt32[2] = [13, 0] // UInt32
        [1] Int32[2] = [6, 1]
        [2] Int8[0] = ['']
        [3] UInt32[6] = [-587202560, 2, 1, 1, 1, 1]
```

If I remember correctly `MatFileRW` renames entries without name, so it should've shown up as `@0`.

**Comment by ennerf** [comment]
However, once the subsystem is parsed it really doesn't matter to users anymore unless they want to serialize it again. It may make sense to remove it from the normal entry list and provide a `getSubsystem()` for the few users who actually need it.

**Comment by piotrszwarnog** [comment]
Sorry for very late reply. Thank you for thorough explanation. I agree with your idea that it might be better not to include subsystem in normal entry list. 
Thanks for help - I'm looking forward to new releases!
