### ISSUE TITLE
AbstractStruct remove method doesn't recompute indexMap

### ISSUE THREAD

**Issue by ryanlb1000** [HebiRobotics/MFL#53]
In the AbstractStruct.remove method, the member "indexMap" stores indices used to access into members "fields" and "values". However when a field is removed, the "indexMap" indices are not adjusted to reflect the possible shift in index values caused by the removals in "fields" and "values".

I reworked this class (locally) to use a LinkedHashMap<String, Array[]>, replacing the three members and maintaining field insertion order. I'm not too familiar with your code/lib needs/standards/etc, but wanted to offer this report. Hope it is helpful!

Thanks,
Ryan

```
@Override
    public Array[] remove(String field) {
        Integer fieldIndex = indexMap.remove(checkNonEmpty(field));
        if (fieldIndex == null)
            throw new IllegalArgumentException("A field named '" + field + "' doesn't exist.");
        fields.remove((int) fieldIndex);
        return values.remove((int) fieldIndex);
    }
```

**Comment by ennerf** [comment]
fixed in 0.5.5
