### ISSUE TITLE
Can i use this library in android studio?

### ISSUE THREAD

**Issue by SoyeonUm** [HebiRobotics/MFL#56]
hello :)

I want to use this library in android studio, but an error is occurred because android studio java.specification.version is always 0.9.

The error message is 
**Caused by: java.lang.NumberFormatException: For input string: "0.9"**

The java version is 1.8, but in wikipedia, it says java.specification.version invariably returns 0.9 independently of the version of Android used.

Is there a way to use this library in android studio?

Thank you :)

**Comment by ennerf** [comment]
Thanks for bringing this up. I thought it should should work, but it's just checking for "Dalvik" and probably breaks on the ART vm. I'm not very familiar with Android, but I'll try to look into it.

**Comment by ennerf** [comment]
I've tried running it on Android and this issue comes up when deleting native buffers used for file IO. The issue will be fixed in the next release.

The current workaround is unfortunately a bit more involved than I expected, but you can work with files by going through buffers. The following code worked for me:


```Java
// Sample data
MatFile mat = Mat5.newMatFile().addArray("test", Mat5.newComplex(2, 2));
File file = new File(getFilesDir(), "test.mat");

// Write file
try(RandomAccessFile raf = new RandomAccessFile(file, "rw")) {
	// Write to buffer
	ByteBuffer buffer = ByteBuffer.allocateDirect((int) mat.getUncompressedSerializedSize());
	mat.writeTo(Sinks.wrap(buffer));

	// Write buffer to disk
	buffer.flip();
	FileChannel channel = raf.getChannel();
	channel.write(buffer);

} catch (Exception e) {
	Log.e(TAG, e.getMessage());
}

// Load file
try {
	byte[] bytes = Files.readAllBytes(file.toPath());
	MatFile loaded = Mat5.newReader(Sources.wrap(bytes)).readMat();
} catch (Exception e) {
	Log.e(TAG, e.getMessage());
}
```
