### ISSUE TITLE
Using Sink problem as an response?

### ISSUE THREAD

**Issue by lwalukie** [HebiRobotics/MFL#63]
I wonder if it is possible to convert sink object to byte array or some stream object to use it next as a response in Spring Boot environment **@RestController** endpoint? I find it pretty easy to generate mat file save it to disk then take the file and send it as a response, but I wanted to avoid saving mat file to disk and rather I wanted to save it directly to stream and send as response, but do not know if possible.

**Comment by ennerf** [comment]
Interesting. Do you mind letting me know what your use case for sending mat files from a webserver?

You can just use an in-memory sink like `Sinks.wrap(BytebBuffer buffer)` or `Sink.wrapNonSeeking(OutputStream outputStream)`. 
The Examples [testCreateAndWriteMatFile](https://github.com/HebiRobotics/MFL/blob/a5e58552cbad42d0963adbc8b0db88de3f070727/mfl-core/src/test/java/us/hebi/matlab/mat/tests/Mat5Examples.java#L78-L97) and [testIncrementalWritesWithMixedConcurrentCompression](https://github.com/HebiRobotics/MFL/blob/a5e58552cbad42d0963adbc8b0db88de3f070727/mfl-core/src/test/java/us/hebi/matlab/mat/tests/Mat5Examples.java#L251-L282) should get you started.

**Comment by lwalukie** [comment]
Oh, yeah - I must overlooked those. Thank you and sorry for confusing.
