### ISSUE TITLE
Reading Matlab string array

### ISSUE THREAD

**Issue by grabarczyk-t** [HebiRobotics/MFL#66]
Is it possible to read [string](https://www.mathworks.com/help/matlab/ref/string.html) arrays with MFL library? If not, are there plans to add it in the future?

I was able to read a Matlab file with a string array, but it is stored in a `McosReference` object, and I don't know what to do with it, how to extract specific string values from it.

**Comment by ennerf** [comment]
Unfortunately, `string` is a handle type that gets stored in an undocumented format. The `McosReference` is something like a pointer to an undocumented data region that stores the actual content. I'd be in favor of adding at least read support, but the last time I looked at it I ran into issues reverse engineering the binary format. 

I'm not aware of any 3rd party library that can parse `string`, but it has been a while since I looked at it. Let me know in case you are aware of one that I could copy. PRs are welcome too.

**Comment by ennerf** [comment]
Here is the data from a previous attempt [https://github.com/HebiRobotics/MFL/blob/43b24e8da07eed5c1ea5dca2c1ef8105d1cd2e3e/mfl-core/src/test/java/us/hebi/matlab/mat/tests/mat5/McosTest.java#L254-L310](McosTest.java#L254-L310)

**Comment by grabarczyk-t** [comment]
Ok, thanks for the info! If I find something I will let you know

In the meantime, I was wondering if you could give me some advice what I could use instead. We have some files that have a vector of strings saved as cell array of character arrays. The problem is when the vector is big it takes a lot of memory to load such file, and we were trying to find some ways to solve that. For example, reading a cell array with 1M strings allocates about 400MB heap memory, while reading a real vector with the same number of values allocates only 8MB of direct memory. I was hoping I could convert this vector to string array, as this is much more memory efficient, but now that I know it is not yet supported I need to find some other solution. Do you have any advice what could we do in this situation? Do you know if there is some other way I could structure this string vector that it could be loaded more efficiently? Or is it possible that this high memory usage is caused by some inefficient handling in the MFL library itself?

**Comment by ennerf** [comment]
Can you tell me a bit more about what your strings look like? Optimizations depend a lot on the contents, i.e., variable length customer names would use a different approach  than a text representation of fixed size hashes.

Generally speaking, every char array (single quotes) requires a a separate object that contains a buffer to hold the contents as well as meta data objects for charset/encoding info. A cell array of char strings `data = {'a', 'b', 'c', 'd'}` requires 5 full `Array` objects for storing 4 bytes of data. Especially on small strings I can see the overhead being a lot larger than the actual content.

Storing double quoted strings `data = {"a", "b", "c", "d"}` adds additional overhead for the references, so besides minor corner cases (long strings that often re-occur), it's likely going to be significantly worse. I assume this is where your 50:1 numbers are coming from?

As long as your dataset does not contain any long strings, the most efficient method would probably be to store the data as a 2D char array `data = [ 'a'; 'b'; 'c'; 'd' ]`, but it does require equal length strings or the use of filler characters like `\0`.

**Comment by grabarczyk-t** [comment]
Ok, thanks for the info!

The strings hold some kind of id, like `SONG_TRANH_CIBIS_966`. The form of the ids is generally consistent within one file, but different files can have different ids, with length ranging from about 10 to about 30 (or possibly more).  

> As long as your dataset does not contain any long strings, the most efficient method would probably be to store the data as a 2D char array

ok, that might work, we'll give it a try. Thanks!

**Comment by ennerf** [comment]
The 2D char array should work well in that case. I'll close this issue, but feel free to re-open in case you are still running into performance issues.
