### ISSUE TITLE
Support for matlab categoricals?

### ISSUE THREAD

**Issue by gundoghusse** [HebiRobotics/MFL#76]
We're currently using matfilerw to write data to mat-files which we later process in matlab, but we would really like to use 'categoricals' since that would significantly reduce the complexity of our code both on the java side and matlab side and those are not supported in matfilerw.
I'm looking at MFL to see if the support is there and did some very quick test code to see how it works. Since I haven't used MFL before, I might be doing it all wrong, but I can't get categorical writing to work with my current attempts (reading them works...(. See below on what I've been trying to do and how it fails

1) Create file in Matlab containing one categorical

animals = categorical({'cats', 'dogs', 'meercats'});
save('cat.mat ', 'animals')

2) Try to read and write back the same categorical using MFL

``

    public static void main(String[] args) throws IOException {
        String dir = ".";

        try(Source source = Sources.openFile(dir + "cat.mat")){
            MatFile mat = Mat5.newReader(source).readMat();

            // Only one entry in cat.mat so we take the first one
            MatFile.Entry entry = mat.getEntries().iterator().next();
		 // This reading works fine and if I print out 'entry', MFL tells me it is indeed a categorical. Good so far.

            // Method 1: Direct write of what we read. Works fine.
            Mat5.writeToFile(mat, dir + "java1.mat");

            // Method 2: Take only the entry and create a new MatFile. Does not work. Bug?
            MatFile matOut = Mat5.newMatFile();
            matOut.addEntry(entry);
            Mat5.writeToFile(matOut, dir + "java2.mat");

            // Use writeEntry(). Does not work at all. Am I using the API wrong?
            Mat5Writer writer = Mat5.newWriter(Sinks.newStreamingFile(dir + "java3.mat"));
            writer.writeEntry(entry);
            writer.flush();
        }
    }
``

3) Try to load results in matlab

>>c=load('java1.mat')

c = 

  struct with fields:

    animals: [cats    dogs    meercats]

>>c=load('java2.mat')
Error using load
Cannot read file <path-redacted>/java2.mat.
 
>> c=load('java3.mat')
Error using load
Unable to read MAT-file <path-redacted>/java3.mat. File might be corrupt.

For reference, the file sizes are:
cat.mat => 592 bytes
java1.mat => 672 bytes
java2.mat => 234 bytes
java3.mat => 106 bytes

Something is not getting written back when method 2 and 3.

I tried also tried the same code but with a mat-file containing an cell array {1,2,3} instead of a categorical and then java1 *and* java2 can be loaded in matlab. java3 still cannot, so I assume I am using the API in an incorrect way there.
Anyway, since I can't use "java2" when having categoricals but it works for cell array of numbers, I assume this is a bug or missing feature in MFL's writer. Based on some quick runs in the debugger, it seems like Method 1 writes back something that is an instance of Mat5Subsystem, which does not get written in method 2 and 3 so how do I get that if I am to create a categorical on the java side?

If they are unsupported, is there any interest in adding support for categoricals or are we a corner-case in using these?

...and I can't deal with markdown, it seems to format this text however it wants to

**Comment by ennerf** [comment]
Unfortunately, most (all?) of the datatypes that MATLAB added over the past few versions, e.g., `string` / `categoricals` etc., are objects with an undocumented format.

We reverse-engineered enough of the format to make them semi-readable, but as far as I know there is not a single 3rd party library that actually supports writing.

**Comment by gundoghusse** [comment]
Thanks for the quick reply. I suspected as much, but since it was possible to write back what I had read with "method 1", I thought there perhaps was more behind the scenes. Is that more or less random that it works to immediately write back the same file or is Mat5File a full binary representation of the file it read?

It would be nice if there was error-handling that could tell that writing of unsupported types was attempted, but I don't know how possible that would be to add.

We'll probably stick with matfilerw for the time being and see if we can find some time to reverse-engineer the categoricals format and add support for it.

**Comment by ennerf** [comment]
> Is that more or less random that it works to immediately write back the same file or is Mat5File a full binary representation of the file it read?

Yes, it keeps a full binary representation of the metadata. Changing the byte offset of the metadata (always at the end of the file) should work, but the contents are read-only.

Here is some info with links on the undocumented parts: https://stackoverflow.com/a/56943418/3574093. Most of the relevant code is in the [McosFileWrapper](https://github.com/HebiRobotics/MFL/blob/fed9a95d175661d1cd48a935effdc0c6c3140661/mfl-core/src/main/java/us/hebi/matlab/mat/format/McosFileWrapper.java) class. You can stream the raw entries with [Mat5TagStreamer](https://github.com/HebiRobotics/MFL/blob/fed9a95d175661d1cd48a935effdc0c6c3140661/mfl-core/src/main/java/us/hebi/matlab/mat/format/Mat5TagStreamer.java).

**Comment by gundoghusse** [comment]
Thanks again. I'll store away your links for when/if we find someone to have a stab at it. Sounds like a great student intern project :)
If you want to close the issue, feel free to do so.

**Comment by ennerf** [comment]
That'd be one hell of a frustrating project. Good luck 😄

**Comment by ennerf** [comment]
I just checked your initial examples again. The `entry` is a reference into the `McosSubsystem`, so examples 2 and 3 do not work because you are only adding the reference-entry without the subsystem-entry that contains the data. Otherwise those types of manipulation should work as is.
