### ISSUE TITLE
Does not fully conform with Java 21

### ISSUE THREAD

**Issue by bbolstad96** [HebiRobotics/MFL#78]
Hello,

I'm interested in using MFL and noted that support for Java 21 is advertised. However, running **jdeps** on **mfl-core-0.5.15.jar** flags several issues:

```
digraph "mfl-core-0.5.15.jar" {
    // Path: C:\Tools\Java21_JDEPS\mfl_jar\mfl-core-0.5.15.jar
   "us.hebi.matlab.mat.util.Unsafe9R$Java9"           -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "us.hebi.matlab.mat.util.Unsafe9R$Java9$1"         -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "us.hebi.matlab.mat.util.UnsafeAccess"             -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "us.hebi.matlab.mat.util.UnsafeAccess$1"           -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "us.hebi.matlab.mat.util.UnsafeByteConverter"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
}
```

Are these known issues? Is there a plan to address them in an upcoming version to be fully compliant with Java 21?

Thanks,
BB

**Comment by ennerf** [comment]
Hi! Yes, that's a known issue. The library has been tested on all versions from Java 6 to 22.

Last time I looked at this, there were still issues with the replacement APIs, and it was better to keep this approach w/ warnings.
